### ISSUE TITLE
remove hyrax references from views

### ISSUE THREAD

**Issue by sephirothkod** [scientist-softserv/west-virginia-university#54]
Remove all references to Hyrax and create new solutions that do not rely on Hyrax so the Bulkrax can work independently.
refs #28

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot and recording.

tested:
- locally bc there is no staging
- [DoleSampleMetadata v3.csv](https://github.com/scientist-softserv/west-virginia-university/files/11046718/DoleSampleMetadata.v3.csv)


<details><summary>Bulkrax was run locally and through the console. (Could not run Bulkrax through staging because of docker set up issues that will be resolved down the line)</summary>

![docker-compose -f docker-compose dev local yml exec web sh 2023-03-22 at 8 40 24 PM](https://user-images.githubusercontent.com/29311858/227097739-bacf14d1-c417-4bc2-8f79-6160f715480c.jpg)

there is a `Ldp::Conflict` error because the test CSV has 1 identifier that appears twice.

https://user-images.githubusercontent.com/29311858/227097854-c70e2f0c-2d91-4514-963a-c1b36f6e1ba1.mp4
</details>

**Comment by DiemBTran** [comment]
Closed because this was an internal issue. There is no staging for clients to test on
