### ISSUE TITLE
Policy Area and Topic are duplicating results into both fields

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/west-virginia-university#72]
# Summary

When importing the dole collection the same metadata is appearing in both Policy Area and Topic.  It should not be duplicating.  

# Acceptance Criteria

- [ ] metadata mapped in Policy Area should appear in policy area
- [ ] metadata mapped in topic should appear in topic 
- [ ] Metadata should not be duplicating between the two fields

# Testing Instructions
Have requested a CSV from Danielle to test against.  
Import the spreadsheet and confirm that the above acceptance criteria is met.  

# Notes
They have the staging for this application.  Test locally and then push code to client.

**Comment by summer-cook** [comment]
@crisr15 did we ever get the spreadsheet from them for this one to test against?

**Comment by crisr15** [comment]
Spreadsheet sent in slack.

**Comment by summer-cook** [comment]
This is happening because both `policy_area` and `topic` map to subject. `policy_area` isn't actually being mapped anywhere in Bulkrax currently, and this duplication is happening further down the line in their application

in their model, the following property mappings exist:

```
  # DC subject
  # ==============================================================================================================
  # Policy Area property
  property :policy_area, predicate: ::RDF::Vocab::DC.subject, multiple: true do |index|
    index.as :stored_searchable, :stored_sortable, :facetable
  end  

  # DC subject
  # ==============================================================================================================
  # Topic property
  property :topic, predicate: ::RDF::URI.intern('http://purl.org/dc/terms/subject'), multiple: true do |index|
    index.as :stored_searchable, :stored_sortable, :facetable
  end
```
in the sample csv provided, there is a header for `dcterms:subject`, which corresponds with `policy_area` but no header that would correspond with `dcterms:http://purl.org/dc/terms/subject`

As an fyi, if they want to add topics, they will need to use a header of `dcterms:http://purl.org/dc/terms/subject` (similarly formatted to `dcterms:http://purl.org/dc/terms/type`)
