### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/west-virginia-university#8]
# Summary

As a user I can export records and metadata.  
Relies on #5  #7  #26  #27

**Comment by sephirothkod** [comment]
still has to wait on #7 being complete.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot. Closing because this is not client testable, since there is no staging

tested on:
- tested locally because there is no staging
- importer's CSV (from which I exported from):  [DoleSampleMetadata v4e.csv](https://github.com/scientist-softserv/west-virginia-university/files/11237490/DoleSampleMetadata.v4e.csv)
- exported CSV (export from importer): [export_3_from_importer_1.csv](https://github.com/scientist-softserv/west-virginia-university/files/11237489/export_3_from_importer_1.csv)

<details><summary>The exported CSV's data matches the data from the importer's CSV</summary>

![export_3_from_importer_1 2023-04-14 at 3 22 08 PM](https://user-images.githubusercontent.com/29311858/232164842-210dc056-30bf-4020-bc7e-2771e4685585.jpg)
</details>
